---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: movies-r-us-cluster
  region: eu-west-1

nodeGroups:
  - name: ng-1
    instanceType: t3.small
    desiredCapacity: 3
    iam:
      attachPolicy:
        Version: "2012-10-17"
        Statement:
        - Effect: Allow
          Action:
          - 's3:GetObject'
